version: "2"

services:

    cam:
        image: alejandrocolomar/rob_cam:cam
        devices:
            - "/dev/video0:/dev/video0"
        environment:
            - CAMERA_IDX=0
#            - DELAY_LOGIN=1000000
            - DELAY_US=10000
            - ROB_ADDR=rob
#            - ROB_CAMS_MAX=1
            - ROB_PORT=13100

    rob:
        image: alejandrocolomar/rob_cam:rob
        environment:
            - DELAY_LOGIN=1000000
            - DELAY_US=100000
            - ROB_CAMS_MAX=10
            - ROB_PORT=13100
            - ROBOT_ADDR=robot
            - ROBOT_PASSWD=
            - ROBOT_PORT=30002
            - ROBOT_STATUS_FNAME=status.log
#            - ROBOT_TYPE=kwr
            - ROBOT_TYPE=ur
            - ROBOT_USER=

    robot:
        image: alejandrocolomar/rob_cam:ur-sim
