###############################################################################
#        Copyright (C) 2020        Sebastian Francisco Colomar Bauza          #
#        Copyright (C) 2020        Alejandro Colomar Andrés                   #
#        SPDX-License-Identifier:  GPL-2.0-only                               #
###############################################################################

version: "2"

services:

    cam:
        image: alejandrocolomar/rob_cam@sha256:d4f0cbda38112ad6ab7345df51d138b065c30ff393bb502a6821925901014117
        devices:
        -   "/dev/video0:/dev/video0"
        environment:
        -   CAMERA_IDX=0
        -   DELAY_US=10000
        -   ROB_ADDR=rob
        -   ROB_PORT=13100
        depends_on:
        -   rob
        restart: always

    rob:
        image: alejandrocolomar/rob_cam@sha256:3725a8c673128861c5dd60f1f98d6c235b2612133494e3ca8e4d2c7abbedca86
        environment:
        -   DELAY_LOGIN=1000000
        -   DELAY_US=100000
        -   ROB_CAMS_MAX=1
        -   ROB_PORT=13100
        -   ROBOT_ADDR=robot
        -   ROBOT_PASSWD=
        -   ROBOT_PORT=30002
        -   ROBOT_STATUS_FNAME=status.log
#        -   ROBOT_TYPE=kwr
        -   ROBOT_TYPE=ur
        -   ROBOT_USER=
        depends_on:
        -   robot
        restart: always

    robot:
        image: alejandrocolomar/rob_cam@sha256:b11e6624f3c7a2205f69c9c89ec4e0ce98cebdd664a41bf9902552567df64bd6
        restart: always

################################################################################
#sudo docker-compose up -d                                                     ;
#sudo docker-compose down                                                      ;
################################################################################
